### PR TITLE
mock the presence of the SSH module

### PR DESCRIPTION
**Pull request by rubys**

### CODE REVIEW

**Comment by stumped2** [comment]
I'm going to create an issue against my repo regarding any modules included in this repo and any assumption of them being up to date or maintained, then I'll merge.

**Comment by stumped2** [comment]
Actually, this specific module might be best to keep under the whimsy project, so that it can better be maintained by the needs of the whimsy project.

**Comment by rubys** [comment]
I'm not following, what do you mean by "under the whimsy project"?

**Comment by stumped2** [comment]
I'm going to close this PR.

The best course of action would (for the time being) to have the whimsy project create this mock module and keep it up to date with [infrastructure-puppet](https://github.com/apache/infrastructure-puppet), and then make a pr against that repo to include the mock module in the [Puppetfile](https://github.com/apache/infrastructure-puppet/blob/deployment/Puppetfile) (with no tag or revision etc).

**Pull request closed without merging**
